package pkg

type Context struct {
	ID string `json:"Id"`

	Period Period `json:"Periodo"`
	Entity Entity `json:"Entidad"`
}

/*
type AutoGenerated struct {
	ID      string `json:"Id"`
	Periodo struct {
		Tipo          int         `json:"Tipo"`
		FechaInstante time.Time   `json:"FechaInstante"`
		FechaInicio   interface{} `json:"FechaInicio"`
		FechaFin      interface{} `json:"FechaFin"`
	} `json:"Periodo"`
	Escenario                      interface{} `json:"Escenario"`
	ContieneInformacionDimensional bool        `json:"ContieneInformacionDimensional"`
	ValoresDimension               []struct {
		Explicita                 bool        `json:"Explicita"`
		IDDimension               string      `json:"IdDimension"`
		IDItemMiembro             string      `json:"IdItemMiembro"`
		QNameDimension            string      `json:"QNameDimension"`
		QNameItemMiembro          string      `json:"QNameItemMiembro"`
		ElementoMiembroTipificado interface{} `json:"ElementoMiembroTipificado"`
	} `json:"ValoresDimension"`
	Entidad struct {
		IDEntidad                      string      `json:"IdEntidad"`
		EsquemaID                      string      `json:"EsquemaId"`
		ID                             string      `json:"Id"`
		Segmento                       interface{} `json:"Segmento"`
		ContieneInformacionDimensional bool        `json:"ContieneInformacionDimensional"`
		ValoresDimension               interface{} `json:"ValoresDimension"`
	} `json:"Entidad"`
}

*/
